#!/bin/sh

### BEGIN INIT INFO
# Provides:             god
# Required-Start:       $all
# Required-Stop:        $all
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    God
### END INIT INFO

REDIS_BIN='/opt/redis/redis-server'
REDIS_PID='/var/run/redis.pid'
REDIS_LOG='/var/log/redis.log'
REDIS_CONFIG='/etc/default/redis'

NAME=redis
DESC=redis

set -e

# Make sure the binary and the config file are present before proceeding
test -x $REDIS_BIN || exit 0

. /lib/lsb/init-functions

RETVAL=0

if [ -f $REDIS_PID ]; then
  echo -n "$DESC already running. Aborting.\n"
  exit $RETVAL
fi;

case "$1" in
  start)
    echo -n "Starting $DESC:\n"
    $REDIS_BIN $REDIS_CONFIG
    RETVAL=$?
    ;;
  stop)
    echo -n "Stopping $DESC:\n"
    kill `cat /var/run/redis.pid`
    rm $REDIS_PID
    RETVAL=$?
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    $REDIS_BIN status
    RETVAL=$?
    ;;
  *)
    echo "Usage: redis {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $RETVAL