#!/bin/sh

### BEGIN INIT INFO
# Provides:             god
# Required-Start:       $all
# Required-Stop:        $all
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    God
### END INIT INFO

GOD_BIN='/usr/local/rvm/bin/bootup_god'
GOD_PID='/var/run/god.pid'
GOD_LOG='/var/log/god.log'
GOD_CONFIG='/etc/default/god'

NAME=god
DESC=god

set -e

# Make sure the binary and the config file are present before proceeding
test -x $GOD_BIN || exit 0

. /lib/lsb/init-functions

RETVAL=0

case "$1" in
  start)
    if [ -f $GOD_PID ]; then
      echo -n "$DESC already running. Aborting.\n"
      exit 0
    fi;
    echo -n "Starting $DESC:\n"
    $GOD_BIN -c $GOD_CONFIG -P $GOD_PID -l $GOD_LOG --log-level debug
    RETVAL=$?
    ;;
  stop)
    echo -n "Stopping $DESC:\n"
    kill `cat /var/run/god.pid`
    rm $GOD_PID
    RETVAL=$?
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    $GOD_BIN status
    RETVAL=$?
    ;;
  *)
    echo "Usage: god {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $RETVAL